# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-11 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State_translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default=None, max_length=50)),
                ('state_language', models.CharField(default=None, max_length=50)),
                ('state_code', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
